### ISSUE TITLE
clone, build then release fails

### ISSUE THREAD

**Issue by adamkiss** [lukeed/fly-kit-web#1]
Hi,

today I found fly, so I was looking for some real world usage, and found this kit. Trying to clone and successfully finish with `release` fails with Parse Error with output from the uglified app.js

What I did: `(clone & cd) && npm install && npm run build && npm run release`
I also tried the same with yarn, but it failed as well.

Node: 6 LTS 
NPM: 4.4.4
Yarn: 0.21.3

Let me know if I can add anything,
thanks.

![screenshot 2017-03-29 23 30 45](https://cloud.githubusercontent.com/assets/481362/24477573/cb52f8be-14d7-11e7-86a3-758c56b7eb2f.png)

**Comment by adamkiss** [comment]
Curiously, installing and running with yarn returns different xo lint results.

**Comment by lukeed** [comment]
Hey, thanks!

I had forgotten to update the task definition for `release`; that was it 😄.

> installing and running with yarn returns different xo lint results

Yeah, this kit includes a `yarn.lock` file, so that means that it's pinned a specific version of XO. Every version of XO includes different rules, so a regular `npm install` fetches the latest + the latest rules.

Thanks for pointing this out! Appreciate it.

**Comment by adamkiss** [comment]
Thank you for fixing this. Just ran `…clone… && yarn && yarn run release` and it works like a charm. 

Just to clarify for me: by moving the build part from the function to the npm command, the release tasks waits until the build is done, right? Thanks. 

> yarn vs. npm

I thought so, just wasn't sure if the yarn.lock wasn't an artifact from one of my previous runs.

**Comment by lukeed** [comment]
No problem!

> the release tasks waits until the build is done, right?

Correct! Passing task names via the CLI are always run in `serial` mode.

**Comment by adamkiss** [comment]
Thank you for awesome work!

**Comment by lukeed** [comment]
Appreciate it -- team effort though 🎉 😄
